services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: energy_monitor
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    ports:
      - "1889:1883"  # Expondo a porta 1889 do host para a 1883 do container
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Mapeando a configuração

volumes:
  mysql_data: